version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    command: "mongod --bind_ip_all --replSet rs0 --keyFile /data/replica.key"
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./data/mongo:/data/db
      - ./keys/replica.key:/data/replica.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: YOUR_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: YOUR_PASSWORD
    entrypoint:
      - bash
      - -c
      - |
          chmod 400 /data/replica.key
          chown 999:999 /data/replica.key
          exec docker-entrypoint.sh $$@