# Run the following:
# > docker-compose up -d
# > docker-compose exec mongo mongo --eval "rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongo:27017'}]});"

# Make sure to include in your /etc/hosts file:
# 127.0.0.1 mongo

version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./data/mongo:/data/db